name = "tadpole"
main = "server-src/server.ts"
compatibility_date = "2025-11-05"

assets = {directory = "./public"}

[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Chat"]
